# This file was generated by nixos-generate-config
# Run: sudo nixos-generate-config --show-hardware-config > hardware-configuration.nix
# Then move it to this location

{ config, lib, pkgs, modulesPath, ... }:

{
  # TODO: Generate this file using: nixos-generate-config --show-hardware-config
  # Place your hardware-specific configuration here
  # For WSL, this may be minimal or empty
}
